version: "3"
services:
  mysql:
    container_name: mysql8
    image: mysql:8
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536