apiVersion: apps/v1
kind: Deployment
metadata:
  name: podoting-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: podoting-server
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: podoting-server
    spec:
      containers:
        - name: podoting-server
          image: ghcr.io/kwanok/podoting-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8080
